version: '2'
services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: m33rk03t
  mariadb:
    image: mariadb:10.2
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: m33rk03t
      MYSQL_DATABASE: prototype_db
      MYSQL_USER: wouter
      MYSQL_PASSWORD: m33rk03t
    restart: on-failure
    volumes:
    - ./mariadb:/var/lib/mysql
  php:
    build: php-fpm
    ports:
      - '9002:9000'
    volumes:
      - ../:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/logs:cached
    links:
      - postgres
  nginx:
    build: nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached